### ISSUE TITLE
customize theme

### ISSUE THREAD

**Issue by capsulecorplab** [startrekthefleet/ussastraeus#1]
theme must include
- [ ] locked background image
- [ ] clickable galleries with "discovery themed" border per gallery cover photo

**Comment by capsulecorplab** [comment]
this will require updating [programmable-matter-hugo-theme](https://github.com/startrekthefleet/programmable-matter-hugo-theme) itself

**Comment by sarasage** [comment]
OBE as per Grav adoption.
